### ISSUE TITLE
(Suggestion) Improve pipeline runtime by using archived data bundle and pigz

### ISSUE THREAD

**Issue by Vlad-Dembrovskyi** [lifebit-ai/pcgr-nf#36]
## Problem
Currently the pipeline takes 16-20 minutes to run even on test data. Majority of that time (13-16 min) is spent on downloading the pcgr reference data. When running the pipeline on CloudOS this will be the case every time you run a pipeline (unles you use the resume option) because the data has to be staged each time to a freshly created machine.

![image](https://user-images.githubusercontent.com/64809705/129490815-bdb2b3af-9f10-42f4-8d17-7be6c9ed7334.png)

The size of reference data is 17-19 Gb (depending on genome build). Which shouldn't be too much for an aws cli download that usually downloads at speed of ~100 Mb/s
![image](https://user-images.githubusercontent.com/64809705/129490905-ce3fbacf-7cc1-4b81-8312-4f467a3bfd94.png)
However when I checked the download speed at which Nextflow stages the files - I was surprised that it hovers around ~10-20 Mb/s. Here is where the long download time comes from. I suggest that this is because the reference data is actually a folder with many many small files in it. I checked, and grch37 folder has 9,596 files in it, and grch38 - 12,313 files:
![image](https://user-images.githubusercontent.com/64809705/129491017-17b3c43b-84fa-42e7-b60e-5bb49c0cb878.png)
Downloading many small files is typically much slower that downloading several big files of same total size, just because of the sheer amount of back-and-forth requests that you have to send for many small files, and/or inability to download data in large chunks.

## Suggestion
Would it be beneficial to have the reference data in a compressed tar archive? Technically that would be a single file and it could be downloaded at the fastest aws speed of 100-120 Mb/s, reducing the download time dramatically. I've put it into test, and its actually the case:
(I used .tar.gz file instead of regular pcgr folder just to see how fast nextflow mounts it. Of course the pipeline was not prepared to handle the archive as reference and failed, but you can see the time it took to stage the file)
![image](https://user-images.githubusercontent.com/64809705/129491170-4a6a0d6d-4736-4b24-9c85-9f7ed091cf82.png)

So technically that reduces the download time by 75-80%. But you still need to unpack the archive, which will reduce the time gained by this solution, but it may still be worth it. So we need to check how long will it take to untar the archive. There are several options.

First of all it must be noted that all the files in pcgr data folder are already gzipped by themselves, and the size of resulting archive is actually the same as the size of initial folder. So maybe we can exclude compression from the archiving process and have it simply as tar.
![image](https://user-images.githubusercontent.com/64809705/129491417-ad4057cc-78e4-4497-b078-af146ba637bf.png)

Secondly, we may use a multi-threaded compression tool such as [pigz](https://zlib.net/pigz/) (read "pig-zee") to decompress faster. I tested decompression with both gzip and pigz and pigz is slightly faster at 4 cores, but may get even faster on more cores:
![image](https://user-images.githubusercontent.com/64809705/129491483-2d74b021-ebf8-4ae0-9ba8-3fdd692517db.png)

We may still want to use the compression simply because it speeds up the compression step, and may be its required to have tar compressed in multithreaded mode to be able to decompress in multi-threaded mode, but I don't know.

So in the end we may just use a tar without compression/decompression if untarring takes the same time. With options above it is 3 min. Together with download of 4 min it is 7 min, which is still twice smaller than 16 min that we have now.

## Tasks
If we decide to check the suggested improvement, here is what has to be done:
- [ ] figure out the fastest way to download and untar the archive. Options: use best possible compression (`--9`) to actually make the file smaller, not use compression at all if its not significant and untarring uncompressed archive takes same time.
- [ ] implement a process that will untar the archive (possibly with [pigz](https://zlib.net/pigz/)) if the imput pcgr data file is not folder but tar archive
- [ ] add [pigz](https://zlib.net/pigz/) to used docker container if decided to use pigz
- [ ] test pipeline with same test data locally and on cloudos to see the time difference to runs when not using compressed reference data.

**Comment by Vlad-Dembrovskyi** [comment]
pigz was not used because didn't give time improvement on decompression. It uses only one core to decompress. Other then that pipeline does support now input of tarball instead of folder, however it hasn't been proven as faster.
